function I_dJr_G = I_dJr_G_fun(in1,in2)
%I_DJR_G_FUN
%    I_DJR_G = I_DJR_G_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    09-Nov-2022 09:18:32

I_dJr_G = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
